### ISSUE TITLE
No such file or directory /home/xychen/new_transformer/nnUNetFrame/DATASET/nnUNet_preprocessed/Task004_BrainTumour/nnUNetPlansv2.1_plans_3D.pkl`

### ISSUE THREAD

**Issue by panovr** [282857341/nnFormer#109]
I put `model_best.model` and  `model_best.model.pkl` to the folder:
`xxx/project/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task003_tumor/nnFormerTrainerV2_nnformer_tumor__nnFormerPlansv2.1/fold_0`

and use the command for inference
```
nnFormer_predict -i /home/zyl/project/nnFormer/DATASET/nnFormer_raw/nnFormer_raw_data/Task003_tumor/imagesTs \
                 -o /home/zyl/project/nnFormer/DATASET/nnFormer_raw/nnFormer_raw_data/Task003_tumor/inferTS/nnformer_tumor \
                 -m 3d_fullres \
                 -t 3 \
                 -f 0 \
                 -chk model_best \
                 -tr nnFormerTrainerV2_nnformer_tumor
```

However, there are the errors:
```
using model stored in  /home/zyl/project/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task003_tumor/nnFormerTrainerV2_nnformer_tumor__nnFormerPlansv2.1
###############################################
I am running the following nnFormer: 3d_fullres
My trainer class is:  <class 'nnformer.training.network_training.nnFormerTrainerV2_nnformer_tumor.nnFormerTrainerV2_nnformer_tumor'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'FLAIR', 1: 'T1w', 2: 't1gd', 3: 'T2w'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([138, 170, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/zyl/project/nnFormer/DATASET/nnFormer_preprocessed/Task003_tumor/nnFormerData_plans_v2.1
###############################################
This model expects 4 input modalities for each image
Found 24 unique case ids, here are some examples: ['BRATS_331' 'BRATS_077' 'BRATS_139' 'BRATS_076' 'BRATS_077' 'BRATS_139'
 'BRATS_114' 'BRATS_325' 'BRATS_331' 'BRATS_190']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 24
number of cases that still need to be predicted: 24
emptying cuda cache
loading parameters for folds, [0]
Traceback (most recent call last):
  File "/home/zyl/anaconda3/envs/nnformer/bin/nnFormer_predict", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_predict')())
  File "/home/zyl/project/nnFormer/nnformer/inference/predict_simple.py", line 229, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/zyl/project/nnFormer/nnformer/inference/predict.py", line 633, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/zyl/project/nnFormer/nnformer/inference/predict.py", line 185, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision, checkpoint_name=checkpoint_name)
  File "/home/zyl/project/nnFormer/nnformer/training/model_restore.py", line 161, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "%s.model.pkl" % checkpoint_name), fp16=mixed_precision,folder=folder)
  File "/home/zyl/project/nnFormer/nnformer/training/model_restore.py", line 111, in restore_model
    trainer = tr(*init)
  File "/home/zyl/project/nnFormer/nnformer/training/network_training/nnFormerTrainerV2_nnformer_tumor.py", line 57, in __init__
    self.load_plans_file()    
  File "/home/zyl/project/nnFormer/nnformer/training/network_training/nnFormerTrainer.py", line 326, in load_plans_file
    self.plans = load_pickle(self.plans_file)
  File "/home/zyl/anaconda3/envs/nnformer/lib/python3.9/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 49, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xychen/new_transformer/nnUNetFrame/DATASET/nnUNet_preprocessed/Task004_BrainTumour/nnUNetPlansv2.1_plans_3D.pkl'
```

Th Brain tumor task should be `Task003_tumor`, I just wonder why the `/home/xychen/new_transformer/nnUNetFrame/DATASET/nnUNet_preprocessed/Task004_BrainTumour/nnUNetPlansv2.1_plans_3D.pkl` comes from.
Thanks!

**Comment by PHPJava666** [comment]
I'm having the same problem, did you solve it?

**Comment by whdong-whu** [comment]
I solved it by modifying the variable ‘init' in the function 'restore_model' in the file ’./nnFormer/nnformer/training/model_restore.py‘, like this:
    init_list = list(init)
    init_list[0] = '/home/nnFormer/DATASET/nnFmer_preprocessed/Task001_ACDC/nnFormerPlansv2.1_plans_3D.pkl'
    init_list[3] = '/home/nnFormer/DATASET/nnFmer_preprocessed/Task001_ACDC'
    init = tuple(init_list)
