### ISSUE TITLE
进行推理时卡住了，是我内存不足么

### ISSUE THREAD

**Issue by zhangjin506** [282857341/nnFormer#33]
(nnFormer) toolman@modeling506:~/Heart_model/zhang/nnFormer/nnformer$ nnFormer_predict -i ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/imagesTs -o ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output -m 3d_fullres -f 0 -t 2 -chk model_best -tr nnFormerTrainerV2_Synapse
using model stored in  /home/toolman/Heart_model/zhang/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_Synapse__nnFormerPlansv2.1
This model expects 1 input modalities for each image
Found 20 unique case ids, here are some examples: ['img0071' 'img0066' 'img0065' 'img0062' 'img0065' 'img0077' 'img0071'
 'img0077' 'img0068' 'img0061']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 20
number of cases that still need to be predicted: 20
emptying cuda cache
loading parameters for folds, [0]
2021-11-12 17:16:46.648260: Using dummy2d data augmentation
I am using the pre_train weight!!
using the following model files:  ['/home/toolman/Heart_model/zhang/nnFormer/DATASET/nnFormer_trained_models/nnFormer/3d_fullres/Task002_Synapse/nnFormerTrainerV2_Synapse__nnFormerPlansv2.1/fold_0/model_best.model']
starting preprocessing generator
starting prediction...
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0061.nii.gz
using preprocessor GenericPreprocessor
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0062.nii.gz
using preprocessor GenericPreprocessor
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0063.nii.gz
using preprocessor GenericPreprocessor
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0064.nii.gz
using preprocessor GenericPreprocessor
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0065.nii.gz
using preprocessor GenericPreprocessor
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0066.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 90, 512, 512) after crop: (1, 90, 512, 512) spacing: [5.         0.94599998 0.94599998] 

before crop: (1, 95, 512, 512) after crop: (1, 95, 512, 512) spacing: [5.         0.79492199 0.79492199] 

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
before crop: (1, 138, 512, 512) after crop: (1, 138, 512, 512) spacing: [3.         0.68359375 0.68359375] 

before crop: (1, 171, 512, 512) after crop: (1, 171, 512, 512) spacing: [3.         0.83789062 0.83789062] 

before crop: (1, 159, 512, 512) after crop: (1, 159, 512, 512) spacing: [3.         0.77734375 0.77734375] 

before crop: (1, 152, 512, 512) after crop: (1, 152, 512, 512) spacing: [3.         0.73046875 0.73046875] 

separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 3
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([3.        , 0.68359375, 0.68359375]), 'spacing_transposed': array([3.        , 0.68359375, 0.68359375]), 'data.shape (data is transposed)': (1, 138, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 138, 462, 462)} 

(1, 138, 462, 462)
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0067.nii.gz
using preprocessor GenericPreprocessor
separate z, order in z is 0 order inplane is 1
predicting ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0061.nii.gz
I am here !!!
True
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 138, 462, 462)
patch size: [ 64 128 128]
steps (x, y, and z): [[0, 25, 49, 74], [0, 56, 111, 167, 223, 278, 334], [0, 56, 111, 167, 223, 278, 334]]
number of tiles: 196
computing Gaussian
separate z, order in z is 0 order inplane is 1
Traceback (most recent call last):
  File "/home/toolman/anaconda3/envs/nnFormer/bin/nnFormer_predict", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_predict')())
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/inference/predict_simple.py", line 230, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/inference/predict.py", line 639, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/inference/predict.py", line 223, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/training/network_training/nnFormerTrainerV2_Synapse.py", line 230, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/training/network_training/nnFormerTrainer_synapse.py", line 524, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/neural_network.py", line 150, in predict_3D
    verbose=verbose)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/neural_network.py", line 387, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/neural_network.py", line 524, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/Swin_Unet_l_gelunorm.py", line 935, in forward
    skips = self.model_down(x)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/Swin_Unet_l_gelunorm.py", line 781, in forward
    x_out, S, H, W, x, Ws, Wh, Ww = layer(x, Ws, Wh, Ww)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/Swin_Unet_l_gelunorm.py", line 431, in forward
    x = blk(x, attn_mask)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/Swin_Unet_l_gelunorm.py", line 265, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x)))
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/Heart_model/zhang/nnFormer/nnformer/network_architecture/Swin_Unet_l_gelunorm.py", line 30, in forward
    x = self.fc1(x)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/toolman/anaconda3/envs/nnFormer/lib/python3.6/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([3.        , 0.73046875, 0.73046875]), 'spacing_transposed': array([3.        , 0.73046875, 0.73046875]), 'data.shape (data is transposed)': (1, 152, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 152, 494, 494)} 

(1, 152, 494, 494)
preprocessing ../DATASET/nnFormer_raw/nnFormer_raw_data/Task002_Synapse/inferTs/output/img0071.nii.gz
using preprocessor GenericPreprocessor
before: {'spacing': array([3.        , 0.77734375, 0.77734375]), 'spacing_transposed': array([3.        , 0.77734375, 0.77734375]), 'data.shape (data is transposed)': (1, 159, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 159, 525, 525)} 

(1, 159, 525, 525)
before crop: (1, 173, 512, 512) after crop: (1, 173, 512, 512) spacing: [3.        0.8359375 0.8359375] 

before crop: (1, 110, 512, 512) after crop: (1, 110, 512, 512) spacing: [5.         0.88085938 0.88085938] 

before: {'spacing': array([3.        , 0.83789062, 0.83789062]), 'spacing_transposed': array([3.        , 0.83789062, 0.83789062]), 'data.shape (data is transposed)': (1, 171, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 171, 566, 566)} 

before: {'spacing': array([5.        , 0.79492199, 0.79492199]), 'spacing_transposed': array([5.        , 0.79492199, 0.79492199]), 'data.shape (data is transposed)': (1, 95, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 158, 537, 537)} 

(1, 171, 566, 566)
separate z, order in z is 0 order inplane is 3
(1, 158, 537, 537)
separate z, order in z is 0 order inplane is 3
before: {'spacing': array([5.        , 0.94599998, 0.94599998]), 'spacing_transposed': array([5.        , 0.94599998, 0.94599998]), 'data.shape (data is transposed)': (1, 90, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 150, 639, 639)} 

(1, 150, 639, 639)
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([3.       , 0.8359375, 0.8359375]), 'spacing_transposed': array([3.       , 0.8359375, 0.8359375]), 'data.shape (data is transposed)': (1, 173, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 173, 565, 565)} 

(1, 173, 565, 565)
separate z, order in z is 0 order inplane is 1
before: {'spacing': array([5.        , 0.88085938, 0.88085938]), 'spacing_transposed': array([5.        , 0.88085938, 0.88085938]), 'data.shape (data is transposed)': (1, 110, 512, 512)} 
after:  {'spacing': array([3.        , 0.75781244, 0.75781244]), 'data.shape (data is resampled)': (1, 183, 595, 595)} 

(1, 183, 595, 595)

您好，作者，我在使用synapse数据进行推理时卡住了，是我内存不足么？

**Comment by zhangjin506** [comment]
作者，您好，我又换了个11G的显卡跑，这次没有报错
