### ISSUE TITLE
raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. 

### ISSUE THREAD

**Issue by nothingtosay-l** [282857341/nnFormer#34]
很抱歉打扰您！作者大大知道这个是什么原因吗？
raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full`

**Comment by 282857341** [comment]
这个问题我也遇到过，你把报错信息网上翻，这个错不是真正的报错原因，或者你把完整的报错信息复制下来

**Comment by nothingtosay-l** [comment]
2021-11-13 15:09:13.920591: lr: 0.01
using pin_memory on device 0
Exception in background worker 1:
 Cannot load file containing pickled data when allow_pickle=False
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/nnFormer/bin/nnFormer_train", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_train')())
  File "/home/lab/nnFormer/nnFormer/nnformer/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/home/lab/nnFormer/nnFormer/nnformer/training/network_training/nnFormerTrainerV2_Synapse.py", line 453, in run_training
    ret = super().run_training()
  File "/home/lab/nnFormer/nnFormer/nnformer/training/network_training/nnFormerTrainer.py", line 319, in run_training
    super(nnFormerTrainer, self).run_training()
  File "/home/lab/nnFormer/nnFormer/nnformer/training/network_training/network_trainer.py", line 443, in run_training
    _ = self.tr_gen.next()
  File "/home/lab/anaconda3/envs/nnFormer/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/home/lab/anaconda3/envs/nnFormer/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/home/lab/anaconda3/envs/nnFormer/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by 282857341** [comment]
Cannot load file containing pickled data when allow_pickle=False是真正的报错原因，应该是加载数据的时候出了问题。
可能是numpy的版本问题，你可以检查一下版本
或者试一下在
https://github.com/282857341/nnFormer/blob/e69edc83c79a6a8ccbf634e0ffbdfc82077c277e/nnformer/training/dataloading/dataset_loading.py#L155 里的np.load都加上np.load("xxx", allow_pickle=True)

**Comment by nothingtosay-l** [comment]
好的！感谢！
