### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by zhuofalin** [282857341/nnFormer#42]
当我在运行该项目时，出现“**ValueError: need at least one array to concatenate**”的错误。报错的位置是：
_target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)_

这个问题怎么解决呀？

**Comment by 282857341** [comment]
这个报错位置 不是很清晰，最好能提供完整的报错信息

**Comment by scwuchung** [comment]
> 当我在运行该项目时，出现“**ValueError: need at least one array to concatenate**”的错误。报错的位置是： _target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)_
> 
> 这个问题怎么解决呀？

你好，请问你解决了吗？我也遇到了这个问题

**Comment by scwuchung** [comment]
> 在预处理时出现了问题
Task001_ACDC
number of threads:  (8, 8)

C:\ProgramData\Anaconda3\envs\nnFormer\Lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\ProgramData\Anaconda3\envs\nnFormer\Lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
Are we using the nonzero mask for normalizaion? OrderedDict([(0, False)])
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nnFormer\Scripts\nnFormer_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnformer', 'console_scripts', 'nnFormer_plan_and_preprocess')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\wh\download\nnformer-main\nnformer\experiment_planning\nnFormer_plan_and_preprocess.py", line 126, in main
    exp_planner.plan_experiment()
  File "e:\wh\download\nnformer-main\nnformer\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
    target_spacing = self.get_target_spacing()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\wh\download\nnformer-main\nnformer\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
                           ^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in vstack
  File "C:\ProgramData\Anaconda3\envs\nnFormer\Lib\site-packages\numpy\core\shape_base.py", line 296, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate

**Comment by coptersack** [comment]
我也有这个问题，具体是哪里有问题我好像知道了。
对于MSD中的脑肿瘤数据集，格式为MRI，在计划中对于MRI数据是不收集intensityproperties的，在nnFormer_plan_and_preprocess.py中的144行写明了：
collect_intensityproperties = True if (("CT" in modalities) or ("ct" in modalities)) else False

只有CT图像才会收集intensityproperties，对于脑肿瘤数据集的pkl描述为：
{'all_sizes': [], 'all_spacings': [], 'all_classes': [1, 2, 3], 'modalities': {0: 'FLAIR', 1: 'T1w', 2: 't1gd', 3: 'T2w'}, 'intensityproperties': None, 'size_reductions': OrderedDict()}

其中的all size、all spacing以及intensityproperties都为空，但是在之后的计划中要对spacing和size进行处理，就是在对spacing的concatenate中出现问题。

但是具体怎么改我也不知道。
