### ISSUE TITLE
nnformer_acdc

### ISSUE THREAD

**Issue by Yffy123456** [282857341/nnFormer#93]
nnformer_acdc flops
/home/wf/anaconda3/envs/nnFormer0/bin/python /home/wf/nnFormerFrame/nnFormer0/nnformer/network_architecture/nnFormer_acdc.py
Traceback (most recent call last):
File "/home/wf/nnFormerFrame/nnFormer0/nnformer/network_architecture/nnFormer_acdc.py", line 971, in
nnF = nnFormer(crop_size=[64, 128, 128], num_classes=8)
File "/home/wf/nnFormerFrame/nnFormer0/nnformer/network_architecture/nnFormer_acdc.py", line 932, in init
self.model_down=Encoder(pretrain_img_size=crop_size,window_size=window_size,embed_dim=embed_dim,patch_size=patch_size,depths=depths,num_heads=num_heads,in_chans=input_channels,down_stride=down_stride)
File "/home/wf/nnFormerFrame/nnFormer0/nnformer/network_architecture/nnFormer_acdc.py", line 752, in init
layer = BasicLayer(
File "/home/wf/nnFormerFrame/nnFormer0/nnformer/network_architecture/nnFormer_acdc.py", line 495, in init
self.shift_size = [window_size[0] // 2,window_size[1] // 2,window_size[2] // 2]
TypeError: 'int' object is not subscriptable

**Comment by Overflowu1** [comment]
hi bro,do you fix that bug?The same error happen in my project.T_T
